In [4]:
import numpy as np

In [5]:
qtd = [4,26,54,152]
custo = [100, 150, 220, 450]

In [6]:
arr1 = np.array(qtd)

In [7]:
arr2 = np.array(custo)

In [8]:
estoque = arr1*arr2

In [9]:
estoque

array([  400,  3900, 11880, 68400])

In [10]:
# Exemplo - Cálculo de lucro utilizando arrays

In [11]:
custo = [100,250,345,512]
venda = [165,312,430,640]

In [12]:
arr3 = np.array(custo)

In [13]:
arr4 = np.array(venda)

In [14]:
lucro = arr4 - arr3

In [15]:
lucro

array([ 65,  62,  85, 128])

In [16]:
# Função arange()

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [19]:
np.arange(10,51,2,dtype=float)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [20]:
# Função linspace()

In [21]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [23]:
# Random - rand, randn e randint

In [24]:
np.random.rand(10)

array([0.41008287, 0.50799831, 0.1223202 , 0.73121142, 0.29404762,
       0.52304112, 0.64376451, 0.1276443 , 0.12969882, 0.69184249])

In [25]:
np.random.randn(15)

array([ 0.67021935,  1.39274389, -0.04770348, -0.01445193, -1.04420643,
        0.22510984,  0.15790221,  0.48129809, -0.12923523, -2.36563188,
        0.51957954, -0.31379727, -0.5062888 ,  0.81576257,  0.32286009])

In [26]:
np.random.randint(10,100,30) # (inicio, fim, quantidade)

array([35, 32, 43, 83, 93, 77, 96, 70, 39, 45, 16, 68, 89, 96, 90, 55, 52,
       94, 91, 53, 13, 37, 25, 95, 49, 72, 26, 72, 99, 20])

In [27]:
# zeros e ones

In [29]:
np.zeros((5,4)) # ((linhas,colunas))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.eye(6) # Criação de uma matriz com a diagonal 1

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])