In [34]:
import numpy as np

In [35]:
qtd = [4,26,54,152]
custo = [100, 150, 220, 450]

In [36]:
arr1 = np.array(qtd)

In [37]:
arr2 = np.array(custo)

In [38]:
estoque = arr1*arr2

In [39]:
estoque

array([  400,  3900, 11880, 68400])

In [40]:
# Exemplo - Cálculo de lucro utilizando arrays

In [41]:
custo = [100,250,345,512]
venda = [165,312,430,640]

In [42]:
arr3 = np.array(custo)

In [43]:
arr4 = np.array(venda)

In [44]:
lucro = arr4 - arr3

In [45]:
lucro

array([ 65,  62,  85, 128])

In [46]:
# Função arange()

In [47]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
np.arange(10,21,2)

array([10, 12, 14, 16, 18, 20])

In [50]:
np.arange(10,51,2,dtype=float)

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38., 40., 42., 44., 46., 48., 50.])

In [ ]:
# Função linspace()

In [51]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [52]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])